# Generated by Django 3.2.5 on 2021-07-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllSpent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allspent', models.IntegerField(verbose_name='total spent')),
            ],
        ),
        migrations.AlterField(
            model_name='total',
            name='total',
            field=models.IntegerField(auto_created=0, verbose_name='total maount'),
        ),
    ]
