# Generated by Django 3.2.5 on 2021-07-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210711_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='allspent',
            name='cations',
            field=models.IntegerField(default=None, verbose_name='actions'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='allspent',
            name='allspent',
            field=models.IntegerField(auto_created=0, verbose_name='total spent'),
        ),
    ]
